### ISSUE TITLE
Password hash with leading zeros

### ISSUE THREAD

**Issue by idlesign** [secure-remote-password/implementations#2]
Following the PR https://github.com/idlesign/srptools/pull/7

@yallie, what impact do you think it whould have on .net implementation?

**Comment by yallie** [comment]
Hi Igor,

As far as I see, the PR only affects the computed values if H(I:P) has leading zeros?
I don't think it would affect .net implementation. It keeps the exact length of the numbers,
so it doesn't lose leading zeros when processing integers as byte arrays.

**Comment by idlesign** [comment]
Thank you. Closing this.
